# Generated by Django 5.1.7 on 2025-03-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_due_data_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completion_data',
            new_name='completion_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Nova'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='new', max_length=20),
        ),
    ]
